export class NeedTeacher {
  IDNeedTeacher?:number;
  IDUser?:number;
  Mail?:string;
  FullName?:string;
  Phone?:string;
  IDCity?:number;
  City?:string;
  DatePossible?:Date;
  TimeSlice1?:boolean;
  TimeSlice2?:boolean;
  TimeSlice3?:boolean;
  TimeSlice4?:boolean;
  IDSubject?:number;
  Subject?:string;
  IDLevel?:number;
  Level?:string;
  Comments?:string;
}
